[package]
name = "thriftrs2"
version = "0.2.1"
edition = "2021"
description = "Fast Apache Thrift bindings for Python powered by Rust and PyO3."
readme = "README.md"
license = "MIT"
repository = "https://github.com/CherryLemon/thriftrs2"
homepage = "https://github.com/CherryLemon/thriftrs2"
keywords = ["thrift", "rpc", "serialization", "python", "pyo3"]
categories = ["api-bindings", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "thriftrs2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["experimental-async"] }
serde = { version = "1.0", features = ["derive"] }
nom = "8.0.0"
serde_json = "1.0"
byteorder = "1.5"
thiserror = "2.0.18"
base64 = "0.23"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time", "signal"] }
num_cpus = "1.16"
pyo3-async-runtimes = { version = "0.28.0", features = ["tokio-runtime", "attributes"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
