[package]
name = "thrift_rs_pyo3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "thrift_rs_pyo3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.2"
serde = { version = "1.0", features = ["derive"] }
nom = "8.0.0"
serde_json = "1.0"
byteorder = "1.5"
thiserror = "2.0.18"
base64 = "0.22"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time"] }
num_cpus = "1.16"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
